### ISSUE TITLE
Investigate Cloud-optimized GeoTiffs and/or LZW predictor settings for Tif output

### ISSUE THREAD

**Issue by clairecporter** [PolarGeospatialCenter/imagery_utils#49]

**Comment by ehusby** [comment]
My tests in https://github.com/PolarGeospatialCenter/imagery_utils/pull/60, while not thorough, didn't look very promising on LZW compression savings for tif output with non-1 predictor value settings.

**Comment by clairecporter** [comment]
Erik and Shane's initial findings suggest that predictor settings do not improve compression.
